version: "3.9"
services:
  client:
    image: ghcr.io/jamesalexanderhill/pocketbase-react-app-boilerplate:latest
    container_name: react-client
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - "hestia"
    environment:
      - VIRTUAL_HOST=${APP_URL}
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=${APP_URL}
      - VITE_POCKETBASE_URL=https://pocketbase:8090
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv
      - ENCRYPTION
    environment:
      - ENCRYPTION=${PB_ENCRYPTION}
      - VIRTUAL_HOST=${PB_URL}
      - VIRTUAL_PORT=8090
      - LETSENCRYPT_HOST=${PB_URL}
    networks:
      - "hestia"
    ports:
      - "8090:8090"
    volumes:
      - ./.pocketbase/pb_data:/pb_data
      - ./.pocketbase/pb_public:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  hestia: # you need to create this network on your VPS
    external: true