version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./.pocketbase/data:/pb_data
      - ./.pocketbase/public:/pb_public